import type { Manicurist } from '../types';

export const defaultManicurists: Manicurist[] = [
  { id: 'mani-1',  name: 'Tommy',     color: '#ec4899', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-2',  name: 'Kim',       color: '#8b5cf6', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-3',  name: 'Tammy',     color: '#f59e0b', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-4',  name: 'Sam',       color: '#10b981', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-5',  name: 'Kimberly',  color: '#3b82f6', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-6',  name: 'Ly',        color: '#ef4444', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-7',  name: 'Mia',       color: '#f97316', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-8',  name: 'Hana',      color: '#06b6d4', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-9',  name: 'Katelyn',   color: '#84cc16', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-10', name: 'Panda',     color: '#6366f1', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-11', name: 'Leo',       color: '#14b8a6', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-12', name: 'Ann',       color: '#f43f5e', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-13', name: 'Brian',     color: '#0ea5e9', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-14', name: 'Joe',       color: '#a855f7', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-15', name: 'Christina', color: '#22c55e', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-16', name: 'Kelly',     color: '#eab308', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-17', name: 'Macy',      color: '#d946ef', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
  { id: 'mani-18', name: 'Danny',     color: '#64748b', phone: '', status: 'available', clockedIn: false, clockInTime: null, totalTurns: 0, currentClient: null, skills: [], hasFourthPositionSpecial: false, hasWax: false, hasWax2: false, hasWax3: false, hasCheck2: false, hasCheck3: false, timeAdjustments: {}, pinCode: '', breakStartTime: null, smsOptIn: false },
];
